OBJS=a.o _ae.o bar.o bb.o b.o bmar.o bsale.o _clsc.o cstat.o d.o e.o gamb.o girl.o h.o help.o hp.o i.o inv.o jmp.o k.o kl.o kos.o loa.o mar.o meet.o met.o mh.o ob.o p.o pon.o pr.o raid.o r.o rep.o rsl.o sav.o s.o sl.o so.o ssl.o sstay.o stat.o stdi.o str.o _sv.o sv.o svo.o t.o tok.o trn.o tus.o up.o v.o _vis.o vpl.o _w.o w.o wes.o x.o
CXXFLAGS=-Wall -ggdb

all: $(OBJS)

clean:
	rm -f *.o &>/dev/null &

.PHONY: all clean