name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.59.0

      - name: Setup Conan Profile
        run: conan profile new --detect default

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Archive artifacts for Linux
        uses: actions/upload-artifact@v1
        with:
          name: linux_build
          path: build/gop2

  windows:
    runs-on: windows-latest
    steps:
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.59.0

      - name: Setup Conan profile
        run: conan profile new --detect default

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Archive artifacts for Windows
        uses: actions/upload-artifact@v1
        with:
          name: windows_build
          path: build/${{env.BUILD_TYPE}}/gop2.exe
