name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: cd ${{github.workspace}}/build && ctest --extra-verbose

      - name: Archive artifacts for Linux and MacOS
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os != 'windows-latest' }}
        with:
          name: ${{ matrix.os }}
          path: build/gop2

      - name: Archive artifacts for Windows
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: ${{ matrix.os }}
          path: build/${{env.BUILD_TYPE}}/gop2.exe

  # Memory sanitizer tests on Linux only (memory issues are platform-independent)
  sanitizer-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure CMake with sanitizers
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -g"

      - name: Build with sanitizers
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Run tests with sanitizers
        run: cd ${{github.workspace}}/build && ./gop2_tests
